[package]
name = "binary-ui"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true

[features]
default = ['dev']
dev = ["library-core/debug"]
uat = ['local-ui', "library-core/debug"]
prod = ['local-ui']

local-ui = []

[dependencies]
# tauri 基础组件
wry = { workspace = true }
tao = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
library-web = { path = "../library-web" }
library-core = { path = "../library-core" }
