[package]
name = "binary-works-cloudflare"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
library-nc = {path = "../library-nc"}
